# Generated by Django 4.1.5 on 2023-01-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
