# Generated by Django 4.1.5 on 2023-01-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='empresa',
        ),
    ]
