# Generated by Django 3.2.12 on 2022-12-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20221207_1009'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='Funcionario'),
            preserve_default=False,
        ),
    ]
